# Generated by Django 3.0 on 2021-02-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210206_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredients',
            field=models.CharField(choices=[('easy', 'EASY'), ('middle', 'MIDDLE'), ('hard', 'HARD')], default='tomato', max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'EASY'), ('middle', 'MIDDLE'), ('hard', 'HARD')], default='easy', max_length=12),
        ),
    ]
