# Generated by Django 3.0 on 2021-02-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210206_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'EASY'), ('middle', 'MIDDLE'), ('hard', 'HARD')], default='easy', max_length=8),
        ),
    ]
