# Generated by Django 3.0 on 2021-02-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.CharField(choices=[('tomato', 'TOMATO'), ('egg', 'EGG'), ('milk', 'MILK'), ('bread', 'BREAD'), ('onion', 'ONION')], default='tomato', max_length=6)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'EASY'), ('middle', 'MIDDLE'), ('hard', 'HARD')], default='easy', max_length=6),
        ),
        migrations.AddField(
            model_name='post',
            name='select_ingredients',
            field=models.ManyToManyField(to='blog.Ingredients'),
        ),
    ]
