# Generated by Django 3.0 on 2021-02-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210206_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredients',
            field=models.CharField(choices=[('easy', 'EASY'), ('middle', 'MIDDLE'), ('hard', 'HARD')], default='tomato', max_length=200),
        ),
    ]
