# Generated by Django 3.0 on 2021-02-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210207_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredients',
            field=models.CharField(choices=[('easy', 'EASY'), ('middle', 'MIDDLE'), ('hard', 'HARD')], max_length=200, null=True),
        ),
    ]
